services:
  db:
    image: postgres:16
    container_name: gpa-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gov_procurement
    ports:
      - "5432:5432"
    volumes:
      - gpa_pg_data:/var/lib/postgresql/data

volumes:
  gpa_pg_data:
